{{ subline(user) }} ({{ url_for("pybble.views.detail_oid", _external=True, oid=user.oid()) }})
hat einen Berechtigungseintrag „{{ subline(obj) }}“
({{ url_for("pybble.views.view_oid", _external=True, oid=obj.oid()) }})
für den Datensatz „{{ subline(obj.parent) }}“ ({{  url_for("pybble.views.view_oid", _external=True, oid=obj.parent.oid()) }})
und den Benutzer bzw. die Gruppe „{{ subline(obj.owner) }}“ ({{  url_for("pybble.views.view_oid", _external=True, oid=obj.owner.oid()) }})
angelegt:
-----
{{ obj.data|safe }}
-----
PS: Der Tracker, der diese Mail generiert hat, ist hier:
{{ url_for("pybble.views.view_oid", _external=True, oid=tracker.oid()) }}
